version: '2'
services:
    testjhipsterci-app:
        image: testjhipsterci
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testjhipsterci-mysql:3306/testjhipsterci?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testjhipsterci-mysql:
        extends:
            file: mysql.yml
            service: testjhipsterci-mysql
